using UnityEngine;

public class GameManager : MonoBehaviour {

    public static GameManager Singleton;

	public static InputSystem_Actions.DebugActions DebugActions => Singleton._inputActions.Debug;
	public static InputSystem_Actions.PlayerActions PlayerActions => Singleton._inputActions.Player;

	InputSystem_Actions _inputActions;



	private void Awake() {
		if (!Singleton) {
			Singleton = this;
			DontDestroyOnLoad(gameObject);

			_inputActions = new();
		} else if (Singleton != this) {
			Destroy(gameObject);
		}
	}

	private void OnDestroy() {
		if (Singleton == this) {
			Singleton = null;
		}
	}

}

/*
<	^		^	>
<	^		>
	#	
	<		v		>
	v



E1L	P1		E4U	E1R
E5L	P5		P4
	^
	P2		P3		E3R
	E2D


3	4	5	4	5
2	1	2	3
3	0		4
|	<		5		>
	v





a tricky issue with the way this puzzle works is that pieces of travel time. Consider a generator that works like this: start with a random position and direction (horizontal or vertical). Put three pucks in the same direction of that position. The outer two Pucks are assumed to be hit by the middle Puck. Next, alternate the direction but starting at the middle Puck's position this time. The middle puck will not be set as a new middle Puck of the new direction, it will instead be an edge piece, meaning one edge piece and one middle piece will be newly created. Repeat onto the new middle Puck. Continue X times
Consider the following sequence of generation steps, where arrows (<, >, ^, v, #) indicate the direction an instigator (i.e. the Puck hitting this one (a Puck that has been hit is the "instigated")) will hit this instigated Puck, or # if the instigator direction is undecided this step (of course a '-' is an empty space):

1
```
^
-
#
-
v
```

2
```
^----
-----
<--#>
-----
v----
```

3
```
^--^-
---#-
<--v>
-----
v----
```

3
```
^--^----
---<-#->
<--v>---
--------
v-------
```

4
```
^--^----
---<-^->
<--v>---
-----#--
v-------
```

At this point, based on the generation steps, the solution should be to swipe the # Puck upward. However, if we actually try this solution, we run into what's basically a race condition. Here is a visual of running the supposed solution, where numbers indicate steps (we can assume discrete movements of the Pucks, even though in practice they will be interpolated for smoother visuals):
```
87656785
9--43234
876561-5
9----0-6
A-------
```
As can be seen by the step numbers, the top left Puck and the middle left Puck are both hit by step 8. In the case of this level, the puzzle will still end up as solved, since there will only be one Puck level at step 8 (the bottom left Puck) and that will be hit by the middle left Puck eventually, just like how the generated level expected it to be. However, I'm worried that there may be a puzzle configuration generated by this strategy where the race condition causes the puzzle to become unsolvable. Consider this alteration of the generated puzzle, where we add a piece to the top left:
```
<^--^----
----<-^->
-<--v>---
------#--
-v-------
```
The new top left Puck, <, is meant to be hit by the ^ to its right, but because of the race condition, ^ will be hit from the right, causing it to split up/down, and thus causing < to never get hit.

Though, the simple generation strategy used before wouldn't generate this puzzle, since the new top left Puck being generated would be created with a complementary > in the same row somewhere, causing something like this to be generated instead:
```
<^>-^----
----<-^->
-<--v>---
------#--
-v-------
```
which would still be solvable (the ^ puck in the top middle that previously caused the race condition via its leftward split would safely be guarded by the > puck to its left). But, i'm still worried. Perhaps i should just try to implement this generator instead of worrying, but do you believe my worry is valid? If you believe my worry can be disproven, please do. A formal proof would be great for this, but a simpler explanation is fine as well.k If you believe my worry can be proven, please provide an example level where this simple level generator idea generates a level that such that its solution does not actually solve the puzzle (note: make sure the generated level is actually possible to be generated using the algorithm stated, e.g. the example fail layout is not a valid example because it wouldn't be generated by the algorithm)
*/
